# Introduction to arrays


Today we will be covering
- Importing libraries (well just NumPy for now)
- NumPy functions ("zeros","ones","array","linspace")
- Indexing (calling specific elements of an array)
- Using arrays to solve equations

An array is a fancy coding word for a matrix. This often confused me when I was getting started in coding so just remember, for our purposes... 
# Array = Matrix
Arrays are often used to store data or compute calculations with a range of different values
For example, if you wanted to describe the location of a point in 3D space you could write in the x, y, and z coordinates as separate variables like this...

In [1]:
x=5
y=0
z=1
print(x,y,z)

5 0 1


Or, you could write it as a vector (AKA an array)...


\begin{bmatrix}
5 \\
0 \\
1
\end{bmatrix}


In [1]:
#Letting r=(x,y,z)
r=[5,0,1]
print(r)

[5, 0, 1]


##### Luckily, python has many built in libraries that make array manipulation much easier :)

# Sidenote: Importing Libraries

One of the most useful libraries in physics is known as NumPy (short for Numerical Python). So, how do I access the formidable power known as 'NumPy'?

In [2]:
#It is amazingly simple, just type in
import numpy

After running this cell, we now have access to all of numpy's built in functions. The four we will look at first are...
- "numpy.zeros" which creates an array where all elements inside it are zero
- "numpy.ones" which creates an array where all elements are (you guessed it!) one
- "numpy.array" which allows you to create an array that you can fill in with the values of your choice.
- "numpy.linspace" which creates an array of linearly spaced (hence the name) points within a specified range


So let's look at np.zeros first. Say we want to create an empty 1 dimensional matrix (named NeutrinoData) that we will later fill up with 100 data points from our Neutrino experiment.

In [3]:
#By empty, I simply mean all elements of this matrix/array are zero

NeutrinoData=numpy.zeros(100)

print(NeutrinoData)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### So, you can see that I accessed the built in numpy function called 'zeros' which creates an array that is completely populated with zeros.

####  The general formula for calling numpy functions is...

####  variable = numpy.name_of_function(function inputs)

#### You Try!
Try making an array of only zeros (using numpy.zeros) that has between 20-80 elements. Print this array when done

# Tricks of the Trade
As your coding gets more and more complex, it may get tiresome to be typing numpy before every single function you want to call. Luckily, you can 'rename' numpy when you import it to save a bit of work

In [10]:
#What we did before:
import numpy

#What we're doing now (renames numpy as np so your computer recognizes np to mean numpy)
import numpy as np

#You could also name it something else

import numpy as henryIsTheBest
zero_array=henryIsTheBest.zeros(100)
print(zero_array)

#However, I would definitely NOT reccommend making it something like this!!


#Let's stick with the "Physics Standard"
import numpy as np

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [11]:
#So back to the Neutrino Data set example, we can generate our empty matrix by now writing
NeutrinoData=np.zeros(100)
print(NeutrinoData)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


Next, let's look at numpy.ones! Or more accurately, np.ones! Let's try making a 50 point array of just ones.

In [22]:
NeutrinoData2=np.ones(50)

print(NeutrinoData2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


Are there any questions so far? 
- Do you understand how to import a library?
- Do you understand how to rename a library once it's imported? Do you get why we do that?
- What is the input for np.ones and np.zeros?

# Now onto our 3rd built in function, "np.array"
Remember: np.array is used to create an array that you fill with elements of your choice.

In [8]:
#You may remember that I saved an array earlier by simply typing
r=[5,0,1]
print(r)

#Writing an array this way won't produce any errors, however it is better to write arrays 
#using np.array because it uses much less memory on your computer/server

r=np.array([5,0,1])
print(r)

[5, 0, 1]
[5 0 1]


You can see that using both methods gives essentially the same result and both arrays will work. Some important notes when initializing arrays...
- Always separate individual data points using a *comma*
- Use *square brackets* to enclose your array
- Because np.array is a built in numpy function, you must put it's inputs in round brackets. Thus, when building an array remember to use round brackets AND then square brackets


In [12]:
#Let's try a few examples. First let's initialize an array with the first 6 prime numbers


#Next, lets initialize an array that goes from 0 to 10


#### You Try! 
Make an array using np.array that stores your [birth year, birth month, birth day]. 
i.e for me this would be [2000, 11, 28]

# Now onto the final numpy function we will look at today, np.linspace! 
This one has 3 inputs so is a little trickier to use than the first 3. The inputs are first point, last point, and number of data points desired.

In [23]:
#For example, to getan array from 1 to 11 with 11 linearly spaced points, you would write
example=np.linspace(1,11,num=11)
print(example)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [24]:
#You can also omit using the num=__ part and just type in the number of points you want in the third 'slot'
example2=np.linspace(1,11,11)
print(example2)

#They both give the exact same result so just use whichever you prefer!

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


#### You Try!
Create an array that shows a range between 152.3 and 972.74 using 21 data points

# Calling specific elements of an array (AKA Indexing)

Say I want to access the 5th element of my array, how do I do that?
Simply type in the name of your array with the element you want to access

In [26]:
      #type in line here

Why is it showing the 6th element of the array instead of the 5th?
### Python Indexing starts at 0!
So if you want to call the first element of your array, you would type ArrayName[0]

In [29]:
print(example[0])

#So to access the 5th element of our array, we would type
print(example[4])

1.0
5.0


### General Rule: when indexing, type in the number below the element you want to index
Now, what if you want to access multiple elements of an array?

When writing on paper, we normally use a dash to represent a range. For example, "I want to access elements 5-7 in my array". However, Python uses a colon (:) to represent a range. 

In [30]:
#So if I wanted to actually access these elements, I would type
Elements_5_to_7=example[5:7]

#Remember elements 5 to 7 actually refers to the 6th to 8th numbers in the array (because counting starts at 0)

print(Elements_5_to_7)

[6. 7.]


Note that this range does not include the upper bound of the specified range. You are basically telling the computer to access the 5th element and then the 6th and then STOP accessing when it reaches the 7th element.

If you want to access all elements after a specified point, just don't include an endpoint

In [32]:
All_pts_after_2=example[2:]
print(All_pts_after_2)

[ 3.  4.  5.  6.  7.  8.  9. 10. 11.]


### Question Time! 
I know this part can be especially confusing so please ask!

# Doing math with arrays!!!
This is an area where arrays really show their stuff.

Often in physics, you will be asked to solve an equation with a huge range of input values. For example, a broken spacecraft's current velocity could be modelled by the function below where v_0 is the spaceship's initial velocity, a is the acceleration, and x is the distance travelled by a spaceship. 

\begin{equation}
v=\sqrt{v_0^2+2ax}
\end{equation}

If you wanted to see how fast you're spaceship would be moving for every possible initial velocity between 200-250 m/s, it would be exhausting to calculate these values by hand. Time to summon the power of arrays!

In [21]:
#Let's determine the values of velocity over this range of initial velocities

a=-9.81 #acceleration due to Earth's gravity in [meters/seconds^2]
x=1000 #Let's say the broken spaceship is 1 km above Earth's surface


#Creating an array that includes every value between 200-250 m/s.
v0=np.linspace(200,250,num=51)

#Question: Why would I have used 51 points?


#Applying the equation above to calculate the 
v=np.sqrt(v0**2+2*a*x)

print("For an initial velocity of", v0

[142.7585374  144.15616532 145.54724319 146.93195704 148.31048513
 149.68299837 151.04966071 152.41062955 153.76605607 155.11608556
 156.46085772 157.80050697 159.13516268 160.46494944 161.78998733
 163.11039207 164.42627527 165.73774464 167.04490414 168.34785416
 169.64669169 170.94151046 172.23240113 173.51945136 174.80274597
 176.08236709 177.35839422 178.63090438 179.89997221 181.16567004
 182.42806802 183.68723418 184.94323453 186.19613315 187.44599222
 188.69287215 189.9368316  191.1779276  192.41621553 193.65174928
 194.88458123 196.11476232 197.34234214 198.56736892 199.78988963
 201.00995    202.22759456 203.44286667 204.65580862 205.86646157
 207.07486569]


# Dark Matter example (If time Allows)

Say you are asked to calculate the Dark Matter Density at different densities from the galactic centre with the following equation...

\begin{equation}
\rho_x(r)=\rho_s\frac{2^\gamma}{(r/r_s)^\gamma}
\end{equation}

Given...
\begin{equation}
\rho_s=0.707 kg/m^3
\end{equation}
\begin{equation}
\gamma=1.2
\end{equation}
\begin{equation}
r_s=20000 m
\end{equation}

Calculate the Dark Matter Density for a range of distances from 1 km-100 km